cicd uncomment  commit

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -16,9 +16,9 @@ jobs:
 
         run: echo "Hello, CI/CD!"
  
-      # - name: Simulate an error
+       - name: Simulate an error
 
-      #   run: echo "About to fail" ; exit 1
+        run: echo "About to fail" ; exit 1
  
       - name: Another greeting
 
